version: '2'
services:
    new1-app:
        image: new1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://new1-mariadb:3306/new1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://new1-elasticsearch:9200
        ports:
            - 8080:8080
    new1-mariadb:
        extends:
            file: mariadb.yml
            service: new1-mariadb
    new1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: new1-elasticsearch
